[project]
name = "bloomfilter"
version = "0.0.9"
authors = ["Frank Denis <github@pureftpd.org>"]
description = "Bloom filter implementation"
license = "ISC"
homepage = "https://github.com/jedisct1/rust-bloom-filter"
repository = "https://github.com/jedisct1/rust-bloom-filter"

[lib]
name = "bloomfilter"
path = "src/bloomfilter/lib.rs"

[dependencies.rand]
rand = "*"

[dependencies.bit-vec]
bit-vec = "*"
