[project]

name = "bloomfilter"
version = "0.0.1"
authors = ["Frank Denis <github@pureftpd.org>"]
description = "Bloom filter implementation"
license = "ISC"

[lib]

name = "bloomfilter"
path = "src/bloomfilter/lib.rs"
