[project]
name = "bloomfilter"
version = "1.0.4"
authors = ["Frank Denis <github@pureftpd.org>"]
description = "Bloom filter implementation"
license = "ISC"
homepage = "https://github.com/jedisct1/rust-bloom-filter"
repository = "https://github.com/jedisct1/rust-bloom-filter"
edition = "2018"

[dependencies]
bit-vec = "0.6.3"
rand = "0.8.3"
siphasher = "0.3.5"

[features]
defaults = []
serde = ["siphasher/serde_std", "bit-vec/serde"]
